/* The following code was generated by JFlex 1.6.1 */

package Lex;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

//clase de los token devueltos
class Yytoken {
    Yytoken (int numToken,String token, String tipo, int linea, int columna, boolean error){
        //Contador para el número de tokens reconocidos
        this.numToken = numToken;
        //String del token reconocido
        this.token = new String(token);
        //Tipo de componente léxico encontrado
        this.tipo = tipo;
        //Número de linea
        this.linea = linea;
        //Columna donde empieza el primer carácter del token
        this.columna = columna;

        this.error = error;
    }

//Métodos de los atributos de la clase
    public int numToken;
    public String token;
    public String tipo;
    public int linea;
    public int columna;
    public boolean error;
    //Metodo que devuelve los datos necesarios que escribiremos en un archivo de salida
    public String toString() {
        if(error){
            return token +": "+ tipo+" | [Linea: "+linea+"]";
        }
        return "Token #"+numToken+": "+token+" | Componente léxico: "+tipo+" [Linea: "+linea+"]";
    }
}//Fin clase Yytoken
/* Seccion de opciones y declaraciones de JFlex */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/lex/alexico.flex</tt>
 */
public class AnalizadorLexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\14\1\5\1\7\1\7\1\6\22\0\1\12\1\55\1\0"+
    "\1\13\1\0\1\13\1\64\1\13\2\0\1\57\1\56\1\13\1\1"+
    "\1\13\1\60\12\4\1\0\1\61\1\53\1\52\1\54\2\13\1\40"+
    "\1\3\1\42\1\36\1\10\3\3\1\15\2\3\1\43\1\3\1\46"+
    "\1\51\1\22\1\3\1\50\1\45\1\47\6\3\4\0\1\3\1\0"+
    "\1\21\1\41\1\20\1\35\1\11\1\30\1\25\1\2\1\17\2\2"+
    "\1\32\1\26\1\16\1\24\1\37\1\2\1\23\1\27\1\33\1\31"+
    "\1\34\3\2\1\44\1\62\1\65\1\63\7\0\1\7\71\0\1\13"+
    "\41\0\1\3\7\0\1\3\3\0\1\3\5\0\1\3\6\0\1\3"+
    "\u1f2d\0\1\7\1\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\5\2\1\1\3"+
    "\1\6\1\7\1\5\1\1\10\3\2\1\1\10\1\11"+
    "\1\12\1\7\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\7\1\1\1\21\1\22\1\4\1\23\2\21\1\0"+
    "\2\3\1\0\6\3\1\24\11\3\2\0\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\2\0"+
    "\1\36\2\0\2\3\1\0\22\3\3\0\1\37\1\0"+
    "\3\3\1\0\6\3\1\24\11\3\1\40\1\0\1\3"+
    "\1\0\21\3\1\0\1\3\1\0\17\3\1\24\2\3"+
    "\1\0\16\3\1\0\12\3\1\0\10\3\1\0\7\3"+
    "\1\0\5\3\1\0\3\3\1\0\2\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\u0144\0\u010e"+
    "\0\u017a\0\u01b0\0\66\0\66\0\66\0\u01e6\0\u021c\0\u0252"+
    "\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402"+
    "\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546\0\66\0\66"+
    "\0\66\0\66\0\u057c\0\u05b2\0\66\0\u010e\0\u05e8\0\u010e"+
    "\0\u061e\0\u0654\0\u068a\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798"+
    "\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948"+
    "\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8"+
    "\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e"+
    "\0\u010e\0\u061e\0\u0654\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06"+
    "\0\u0c3c\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6"+
    "\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66"+
    "\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u0b64\0\u10e0"+
    "\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290"+
    "\0\u12c6\0\u12fc\0\242\0\u1332\0\u1368\0\u139e\0\u13d4\0\u140a"+
    "\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u010e\0\u1518\0\u154e\0\u1584"+
    "\0\u15ba\0\u15f0\0\u1626\0\u165c\0\u1692\0\u16c8\0\u16fe\0\u1734"+
    "\0\u176a\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878\0\u18ae\0\u18e4"+
    "\0\u191a\0\u1950\0\u1986\0\u19bc\0\u19f2\0\u1a28\0\u1a5e\0\u1a94"+
    "\0\u1aca\0\u1b00\0\u1b36\0\u1b6c\0\u1ba2\0\u1bd8\0\u1c0e\0\u1c44"+
    "\0\u1c7a\0\u1cb0\0\u1ce6\0\u010e\0\u1d1c\0\u1d52\0\u1d88\0\u1dbe"+
    "\0\u1df4\0\u1e2a\0\u1e60\0\u1e96\0\u1ecc\0\u1f02\0\u1f38\0\u1f6e"+
    "\0\u1fa4\0\u1fda\0\u2010\0\u2046\0\u207c\0\u20b2\0\u20e8\0\u211e"+
    "\0\u2154\0\u218a\0\u21c0\0\u21f6\0\u222c\0\u2262\0\u2298\0\u22ce"+
    "\0\u2304\0\u233a\0\u2370\0\u23a6\0\u23dc\0\u2412\0\u2448\0\u247e"+
    "\0\u24b4\0\u24ea\0\u2520\0\u2556\0\u258c\0\u25c2\0\u25f8\0\u262e"+
    "\0\u2664\0\u269a\0\u26d0\0\u2706\0\u273c\0\u2772\0\u27a8\0\u27de"+
    "\0\u2814\0\u284a\0\u2880\0\u28b6\0\u28ec\0\u2922";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\2\4\1\17"+
    "\1\20\1\2\3\4\1\21\1\22\1\23\2\4\1\24"+
    "\1\25\1\26\1\2\1\4\1\27\1\4\2\2\1\4"+
    "\1\30\4\2\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\4\0\1\45"+
    "\62\0\1\46\2\0\1\47\45\0\1\50\15\0\3\4"+
    "\3\0\2\4\3\0\35\4\14\0\4\51\1\5\3\0"+
    "\2\52\54\51\73\0\1\6\64\0\1\45\41\0\1\53"+
    "\21\0\3\4\3\0\2\4\3\0\1\4\1\54\10\4"+
    "\1\55\22\4\20\0\1\45\11\0\1\56\51\0\3\4"+
    "\3\0\2\4\3\0\2\4\1\57\1\4\1\60\2\4"+
    "\1\61\25\4\16\0\3\4\3\0\2\4\3\0\17\4"+
    "\1\62\15\4\16\0\3\4\3\0\2\4\3\0\2\4"+
    "\1\63\4\4\1\64\25\4\16\0\3\4\3\0\2\4"+
    "\3\0\2\4\1\65\1\4\1\66\2\4\1\67\25\4"+
    "\16\0\3\4\3\0\2\4\3\0\4\4\1\70\7\4"+
    "\1\71\1\72\17\4\16\0\3\4\3\0\1\4\1\73"+
    "\3\0\35\4\16\0\3\4\3\0\1\4\1\74\3\0"+
    "\4\4\1\75\30\4\16\0\3\4\3\0\1\4\1\76"+
    "\3\0\35\4\20\0\1\45\36\0\1\77\26\0\1\45"+
    "\33\0\1\100\31\0\1\45\45\0\1\101\17\0\1\45"+
    "\45\0\1\102\17\0\1\45\45\0\1\103\17\0\1\45"+
    "\45\0\1\104\17\0\1\47\45\0\1\105\3\0\1\106"+
    "\13\0\1\45\45\0\1\107\17\0\1\45\57\0\1\110"+
    "\5\0\1\45\60\0\1\111\4\112\1\47\3\0\2\113"+
    "\54\112\4\0\1\114\62\0\1\115\2\0\1\114\51\0"+
    "\1\115\56\0\1\116\20\0\3\4\3\0\2\4\3\0"+
    "\16\4\1\117\16\4\16\0\3\4\3\0\2\4\3\0"+
    "\16\4\1\120\16\4\33\0\1\121\50\0\3\4\3\0"+
    "\2\4\3\0\3\4\1\122\31\4\16\0\3\4\3\0"+
    "\2\4\3\0\22\4\1\123\12\4\16\0\3\4\3\0"+
    "\2\4\3\0\1\4\1\124\7\4\1\125\23\4\16\0"+
    "\3\4\3\0\2\4\3\0\4\4\1\126\30\4\16\0"+
    "\3\4\3\0\1\4\1\127\3\0\35\4\16\0\3\4"+
    "\3\0\2\4\3\0\20\4\1\130\14\4\16\0\3\4"+
    "\3\0\2\4\3\0\1\4\1\131\33\4\16\0\3\4"+
    "\3\0\2\4\3\0\15\4\1\132\17\4\16\0\3\4"+
    "\3\0\2\4\3\0\15\4\1\133\6\4\1\134\10\4"+
    "\16\0\3\4\3\0\2\4\3\0\15\4\1\135\17\4"+
    "\16\0\3\4\3\0\2\4\3\0\1\4\1\136\33\4"+
    "\16\0\3\4\3\0\2\4\3\0\7\4\1\137\25\4"+
    "\16\0\3\4\3\0\2\4\3\0\11\4\1\140\23\4"+
    "\16\0\3\4\3\0\2\4\3\0\6\4\1\141\26\4"+
    "\16\0\3\4\3\0\2\4\3\0\3\4\1\142\31\4"+
    "\16\0\3\4\3\0\2\4\3\0\16\4\1\143\16\4"+
    "\63\0\1\144\61\0\1\145\26\0\1\114\3\0\2\146"+
    "\60\0\1\147\131\0\1\150\17\0\3\4\3\0\1\4"+
    "\1\151\3\0\6\4\1\152\26\4\16\0\3\4\3\0"+
    "\2\4\3\0\4\4\1\153\30\4\34\0\1\154\47\0"+
    "\3\4\3\0\2\4\3\0\15\4\1\131\17\4\16\0"+
    "\3\4\3\0\2\4\3\0\4\4\1\155\30\4\16\0"+
    "\3\4\3\0\2\4\3\0\13\4\1\156\21\4\16\0"+
    "\3\4\3\0\2\4\3\0\22\4\1\157\12\4\16\0"+
    "\3\4\3\0\2\4\3\0\1\4\1\160\33\4\16\0"+
    "\3\4\3\0\2\4\3\0\1\4\1\161\33\4\16\0"+
    "\3\4\3\0\2\4\3\0\4\4\1\162\30\4\16\0"+
    "\3\4\3\0\2\4\3\0\7\4\1\163\25\4\16\0"+
    "\3\4\3\0\2\4\3\0\2\4\1\164\32\4\16\0"+
    "\3\4\3\0\2\4\3\0\16\4\1\165\16\4\16\0"+
    "\3\4\3\0\2\4\3\0\6\4\1\166\26\4\16\0"+
    "\3\4\3\0\2\4\3\0\12\4\1\131\22\4\16\0"+
    "\3\4\3\0\2\4\3\0\3\4\1\167\31\4\16\0"+
    "\3\4\3\0\2\4\3\0\16\4\1\170\16\4\16\0"+
    "\3\4\3\0\2\4\3\0\22\4\1\171\12\4\16\0"+
    "\3\4\3\0\2\4\3\0\20\4\1\172\14\4\16\0"+
    "\3\4\3\0\2\4\3\0\2\4\1\173\32\4\16\0"+
    "\3\4\3\0\1\4\1\174\3\0\35\4\65\0\1\175"+
    "\31\0\1\176\51\0\1\115\2\0\1\147\51\0\1\115"+
    "\47\0\1\176\27\0\3\4\3\0\2\4\3\0\6\4"+
    "\1\131\26\4\16\0\3\4\3\0\2\4\3\0\4\4"+
    "\1\164\30\4\16\0\3\4\3\0\2\4\3\0\20\4"+
    "\1\177\14\4\33\0\1\200\50\0\3\4\3\0\2\4"+
    "\3\0\3\4\1\201\31\4\16\0\3\4\3\0\2\4"+
    "\3\0\2\4\1\202\32\4\16\0\3\4\3\0\2\4"+
    "\3\0\6\4\1\203\5\4\1\204\20\4\16\0\3\4"+
    "\3\0\2\4\3\0\27\4\1\205\5\4\16\0\3\4"+
    "\3\0\2\4\3\0\16\4\1\206\16\4\16\0\3\4"+
    "\3\0\2\4\3\0\15\4\1\207\17\4\16\0\3\4"+
    "\3\0\2\4\3\0\20\4\1\210\14\4\16\0\3\4"+
    "\3\0\2\4\3\0\4\4\1\211\30\4\16\0\3\4"+
    "\3\0\1\4\1\212\3\0\35\4\16\0\3\4\3\0"+
    "\2\4\3\0\2\4\1\213\32\4\16\0\3\4\3\0"+
    "\2\4\3\0\4\4\1\214\30\4\16\0\3\4\3\0"+
    "\2\4\3\0\7\4\1\215\25\4\16\0\3\4\3\0"+
    "\2\4\3\0\4\4\1\216\30\4\16\0\3\4\3\0"+
    "\2\4\3\0\4\4\1\217\30\4\16\0\3\4\3\0"+
    "\2\4\3\0\1\4\1\220\1\4\1\221\31\4\52\0"+
    "\1\222\31\0\3\4\3\0\2\4\3\0\7\4\1\223"+
    "\25\4\35\0\1\224\46\0\3\4\3\0\2\4\3\0"+
    "\2\4\1\225\32\4\16\0\3\4\3\0\2\4\3\0"+
    "\10\4\1\163\24\4\16\0\3\4\3\0\2\4\3\0"+
    "\2\4\1\226\32\4\16\0\3\4\3\0\1\4\1\227"+
    "\3\0\35\4\16\0\3\4\3\0\2\4\3\0\4\4"+
    "\1\230\30\4\16\0\3\4\3\0\2\4\3\0\6\4"+
    "\1\231\26\4\16\0\3\4\3\0\2\4\3\0\2\4"+
    "\1\232\32\4\16\0\3\4\3\0\2\4\3\0\4\4"+
    "\1\233\30\4\16\0\3\4\3\0\2\4\3\0\6\4"+
    "\1\234\26\4\16\0\3\4\3\0\2\4\3\0\3\4"+
    "\1\235\31\4\16\0\3\4\3\0\2\4\3\0\7\4"+
    "\1\236\25\4\16\0\3\4\3\0\2\4\3\0\1\4"+
    "\1\237\33\4\16\0\3\4\3\0\2\4\3\0\6\4"+
    "\1\240\26\4\16\0\3\4\3\0\2\4\3\0\20\4"+
    "\1\241\14\4\16\0\3\4\3\0\2\4\3\0\6\4"+
    "\1\242\26\4\16\0\3\4\3\0\1\4\1\230\3\0"+
    "\35\4\16\0\3\4\3\0\2\4\3\0\16\4\1\243"+
    "\16\4\54\0\1\244\27\0\3\4\3\0\1\245\1\4"+
    "\3\0\26\4\1\246\6\4\36\0\1\247\45\0\3\4"+
    "\3\0\2\4\3\0\20\4\1\250\14\4\16\0\3\4"+
    "\3\0\2\4\3\0\11\4\1\251\23\4\16\0\3\4"+
    "\3\0\2\4\3\0\6\4\1\252\26\4\16\0\3\4"+
    "\3\0\2\4\3\0\6\4\1\163\26\4\16\0\3\4"+
    "\3\0\2\4\3\0\4\4\1\253\30\4\16\0\3\4"+
    "\3\0\2\4\3\0\20\4\1\254\14\4\16\0\3\4"+
    "\3\0\2\4\3\0\21\4\1\255\13\4\16\0\3\4"+
    "\3\0\2\4\3\0\25\4\1\256\7\4\16\0\3\4"+
    "\3\0\2\4\3\0\14\4\1\257\20\4\16\0\3\4"+
    "\3\0\2\4\3\0\1\4\1\163\33\4\16\0\3\4"+
    "\3\0\2\4\3\0\16\4\1\260\16\4\16\0\3\4"+
    "\3\0\2\4\3\0\2\4\1\261\32\4\16\0\3\4"+
    "\3\0\1\4\1\151\3\0\35\4\16\0\3\4\3\0"+
    "\2\4\3\0\25\4\1\262\7\4\16\0\3\4\3\0"+
    "\2\4\3\0\4\4\1\263\30\4\16\0\3\4\3\0"+
    "\2\4\3\0\1\4\1\264\33\4\16\0\3\4\3\0"+
    "\2\4\3\0\2\4\1\265\32\4\37\0\1\266\44\0"+
    "\3\4\3\0\2\4\3\0\4\4\1\267\30\4\16\0"+
    "\3\4\3\0\2\4\3\0\2\4\1\230\32\4\16\0"+
    "\3\4\3\0\2\4\3\0\16\4\1\270\16\4\16\0"+
    "\3\4\3\0\2\4\3\0\12\4\1\163\22\4\16\0"+
    "\3\4\3\0\2\4\3\0\4\4\1\271\30\4\16\0"+
    "\3\4\3\0\2\4\3\0\4\4\1\272\30\4\16\0"+
    "\3\4\3\0\2\4\3\0\7\4\1\273\25\4\16\0"+
    "\3\4\3\0\2\4\3\0\22\4\1\131\12\4\16\0"+
    "\3\4\3\0\1\4\1\163\3\0\35\4\16\0\3\4"+
    "\3\0\2\4\3\0\27\4\1\274\5\4\16\0\3\4"+
    "\3\0\2\4\3\0\4\4\1\275\2\4\1\273\25\4"+
    "\16\0\3\4\3\0\2\4\3\0\6\4\1\276\26\4"+
    "\16\0\3\4\3\0\1\4\1\277\3\0\35\4\16\0"+
    "\3\4\3\0\2\4\3\0\1\4\1\300\33\4\40\0"+
    "\1\301\43\0\3\4\3\0\2\4\3\0\20\4\1\234"+
    "\14\4\16\0\3\4\3\0\2\4\3\0\4\4\1\302"+
    "\30\4\16\0\3\4\3\0\2\4\3\0\20\4\1\303"+
    "\14\4\16\0\3\4\3\0\2\4\3\0\16\4\1\131"+
    "\16\4\16\0\3\4\3\0\2\4\3\0\1\4\1\304"+
    "\33\4\16\0\3\4\3\0\2\4\3\0\4\4\1\305"+
    "\30\4\16\0\3\4\3\0\2\4\3\0\11\4\1\167"+
    "\23\4\16\0\3\4\3\0\2\4\3\0\5\4\1\306"+
    "\17\4\1\256\2\4\1\307\4\4\16\0\3\4\3\0"+
    "\2\4\3\0\6\4\1\310\26\4\16\0\3\4\3\0"+
    "\1\4\1\311\3\0\35\4\41\0\1\312\42\0\3\4"+
    "\3\0\2\4\3\0\23\4\1\313\1\4\1\314\7\4"+
    "\16\0\3\4\3\0\2\4\3\0\30\4\1\307\4\4"+
    "\16\0\3\4\3\0\2\4\3\0\16\4\1\315\16\4"+
    "\16\0\3\4\3\0\2\4\3\0\20\4\1\316\14\4"+
    "\16\0\3\4\3\0\2\4\3\0\4\4\1\317\30\4"+
    "\16\0\3\4\3\0\1\4\1\320\3\0\35\4\16\0"+
    "\3\4\3\0\2\4\3\0\10\4\1\321\24\4\16\0"+
    "\3\4\3\0\2\4\3\0\4\4\1\163\30\4\37\0"+
    "\1\322\44\0\3\4\3\0\2\4\3\0\24\4\1\323"+
    "\10\4\16\0\3\4\3\0\1\4\1\324\3\0\35\4"+
    "\16\0\3\4\3\0\1\4\1\325\3\0\35\4\16\0"+
    "\3\4\3\0\2\4\3\0\7\4\1\230\25\4\16\0"+
    "\3\4\3\0\2\4\3\0\6\4\1\326\26\4\16\0"+
    "\3\4\3\0\2\4\3\0\1\4\1\327\33\4\16\0"+
    "\3\4\3\0\2\4\3\0\2\4\1\311\32\4\35\0"+
    "\1\330\46\0\3\4\3\0\2\4\3\0\2\4\1\331"+
    "\32\4\16\0\3\4\3\0\2\4\3\0\6\4\1\317"+
    "\26\4\16\0\3\4\3\0\2\4\3\0\1\4\1\332"+
    "\33\4\16\0\3\4\3\0\2\4\3\0\4\4\1\333"+
    "\30\4\16\0\3\4\3\0\2\4\3\0\12\4\1\316"+
    "\22\4\42\0\1\334\41\0\3\4\3\0\1\4\1\335"+
    "\3\0\35\4\16\0\3\4\3\0\1\4\1\305\3\0"+
    "\35\4\16\0\3\4\3\0\2\4\3\0\20\4\1\311"+
    "\14\4\35\0\1\244\46\0\3\4\3\0\2\4\3\0"+
    "\6\4\1\336\26\4\16\0\3\4\3\0\2\4\3\0"+
    "\16\4\1\311\16\4\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10584];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\1\1\11\1\1\1\11\35\1\1\11\1\1"+
    "\1\11\2\1\1\0\2\1\1\0\20\1\2\0\11\11"+
    "\2\0\1\1\2\0\2\1\1\0\22\1\3\0\1\1"+
    "\1\0\3\1\1\0\20\1\1\11\1\0\1\1\1\0"+
    "\21\1\1\0\1\1\1\0\17\1\1\11\2\1\1\0"+
    "\16\1\1\0\12\1\1\0\10\1\1\0\7\1\1\0"+
    "\5\1\1\0\3\1\1\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[222];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

    private int contador;
    private ArrayList<Yytoken> tokens;
    private boolean eliminar;

	private void writeOutputFile() throws IOException{
			String filename = "file.out";
			BufferedWriter out = new BufferedWriter(
				new FileWriter(filename));
            System.out.println("\n*** Tokens guardados en archivo ***\n");
			for(Yytoken t: this.tokens){
				System.out.println(t);
				out.write(t + "\n");
			}
			out.close();
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
      contador = 0;
    tokens = new ArrayList<Yytoken>();
    eliminar = false;
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 220) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	try{
		this.writeOutputFile();
        //System.exit(0);
	}catch(IOException ioe){
		ioe.printStackTrace();
	}

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { if(Character.isUpperCase(yytext().charAt(0))){
                    Yytoken t = new Yytoken(0, "Error", "Los identificadores no pueden iniciar con mayuscula < "+ yytext()+" >", yyline+1, yycolumn, true);
                    tokens.add(t);
                    eliminar = true;
                    return t;
                }
                else
                {
                    Yytoken t = new Yytoken(0, yytext(), "Error: Simbolo no reconocido", yyline+1, yycolumn, true);
                    tokens.add(t);
                    return t;
                }
            }
          case 33: break;
          case 2: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"RESTA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 34: break;
          case 3: 
            { if(!eliminar){
        contador++;
        Yytoken t = new Yytoken(contador,yytext(),"ID",yyline+1,yycolumn,false);
        tokens.add(t);
        return t;
    }
    eliminar = false;
            }
          case 35: break;
          case 4: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"NUM_ENTERO",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 36: break;
          case 5: 
            { //Ignorar
            }
          case 37: break;
          case 6: 
            { //ignorar
            }
          case 38: break;
          case 7: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"CARACTER_ESPECIAL",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 39: break;
          case 8: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"ASIGNACION",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 40: break;
          case 9: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"MENOR_QUE",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 41: break;
          case 10: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"MAYOR_QUE",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 42: break;
          case 11: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SUMA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 43: break;
          case 12: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"MULTIPLICACION",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 44: break;
          case 13: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"DIVISION",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 45: break;
          case 14: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"PUNTO_COMA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 46: break;
          case 15: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"LLAVE_ABRE",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 47: break;
          case 16: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"LLAVE_CIERRA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 48: break;
          case 17: 
            { Yytoken t = new Yytoken(contador,"Error","Número no valido (falta numero antes o despues de < . >)",yyline+1,yycolumn,true);
    tokens.add(t);
    return t;
            }
          case 49: break;
          case 18: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"DECREMENTO_UNO",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 50: break;
          case 19: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"RESTA_ASIGNA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 51: break;
          case 20: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"PALABRA_RESERVADA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 52: break;
          case 21: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"IGUAL_QUE",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 53: break;
          case 22: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"MENOR_IGUAL",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 54: break;
          case 23: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"MAYOR_IGUAL",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 55: break;
          case 24: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"DISTINTO_DE",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 56: break;
          case 25: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"SUMA_ASIGNA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 57: break;
          case 26: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"INCREMENTO_UNO",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 58: break;
          case 27: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"MULTIPLI_ASIGNA",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 59: break;
          case 28: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"OP_LOG_AND",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 60: break;
          case 29: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"OP_LOG_OR",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 61: break;
          case 30: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"NUM_FLOTANTE",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 62: break;
          case 31: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"NUM_EXPONENTE",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 63: break;
          case 32: 
            { contador++;
    Yytoken t = new Yytoken(contador,yytext(),"ALTO",yyline+1,yycolumn,false);
    tokens.add(t);
    return t;
            }
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
